# -*- coding: utf-8 -*-
"""agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQad5or7SwA5eLuQcrTSKjHiSbWiE7Wg
"""

from google.colab import drive
drive.mount('/content/drive')

import os

base = "/content/drive/MyDrive/travel_agent"
print("Exists:", os.path.exists(base))
print(os.listdir(base))

!pip install streamlit langchain langchain-groq pyttsx3 reportlab

agent_path = "/content/drive/MyDrive/travel_agent/agent.py"

agent_code = """
import os
import json
import core

from langchain.agents import initialize_agent, Tool
from langchain_groq import ChatGroq
from langchain.llms import Groq

os.environ['GROQ_API_KEY'] = 'grok api key'

llm = ChatGroq(model='llama-3.3-70b-versatile', temperature=0.2)

def tool_plan_trip(query):
    data=json.loads(query)
    return core.search_flights(data['source'],data['destination'])

tools = [
    Tool(
        name='search_direct_flights',
        func=lambda q: core.search_flights(json.loads(q)['source'],json.loads(q)['destination']),
        description='find direct flights'
    ),
    Tool(
        name='search_via_flights',
        func=lambda q: core.search_via_flights(json.loads(q)['source'],json.loads(q)['destination']),
        description='find one stop flights'
    ),
]

agent = initialize_agent(
    tools,
    llm,
    agent="zero-shot-react-description",
    verbose=True,
)

def ask_agent(message):
    return agent.run(message)
"""

with open(agent_path,"w") as f:
    f.write(agent_code)

print("agent.py saved")
