# -*- coding: utf-8 -*-
"""core.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11pSA_EsxhHgLyvYWQQWmr6bKw6T8naBU
"""

from google.colab import drive
drive.mount('/content/drive')

import os

base = "/content/drive/MyDrive/travel_agent"
data = base + "/data"

os.makedirs(base, exist_ok=True)
os.makedirs(data, exist_ok=True)

print("Folders ready:", base)

core_path = "/content/drive/MyDrive/travel_agent/core.py"

core_code = """
import json

DATA_PATH = '/content/drive/MyDrive/travel_agent/data'

def load_json(name):
    with open(f'{DATA_PATH}/{name}.json','r') as f:
        return json.load(f)

FLIGHTS = load_json('flights')
HOTELS = load_json('hotels')
PLACES = load_json('places')

def search_flights(source, destination):
    return sorted(
        [f for f in FLIGHTS if f['from'].lower()==source.lower() and f['to'].lower()==destination.lower()],
        key=lambda x: x['price']
    )

def search_via_flights(source, destination):
    routes=[]
    for f1 in FLIGHTS:
        for f2 in FLIGHTS:
            if f1['from'].lower()==source.lower() and f2['to'].lower()==destination.lower() and f1['to'].lower()==f2['from'].lower():
                routes.append({
                    'via_city': f1['to'],
                    'first_leg': f1,
                    'second_leg': f2,
                    'total_price': f1['price']+f2['price']
                })
    return sorted(routes,key=lambda x:x['total_price'])

def search_hotels(city):
    return sorted([h for h in HOTELS if h['city'].lower()==city.lower()], key=lambda x:x['price_per_night'])

def search_places(city, preference=None):
    places=[p for p in PLACES if p['city'].lower()==city.lower()]
    if preference:
        places=[p for p in places if preference.lower() in [t.lower() for t in p.get('tags',[])]]
    return places
"""

with open(core_path,'w') as f:
    f.write(core_code)

print("core.py saved")

!pip install reportlab
!pip install pyttsx3
import pyttsx3
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

def speak_budget(budget_dict):
    engine = pyttsx3.init()
    total = budget_dict["total_budget"]
    engine.say(f"Your total estimated trip budget is {total} rupees.")
    engine.runAndWait()

def export_pdf(trip, file_path="/content/trip_plan.pdf"):
    c = canvas.Canvas(file_path, pagesize=letter)
    y = 750

    c.drawString(50, y, "Trip Plan Summary")
    y -= 30

    c.drawString(50, y, trip["trip_summary"])
    y -= 40

    c.drawString(50, y, "Selected Flight:")
    y -= 20
    c.drawString(50, y, str(trip["flight_selected"]))
    y -= 40

    c.drawString(50, y, "Selected Hotel:")
    y -= 20
    c.drawString(50, y, str(trip["hotel_selected"]))
    y -= 40

    c.drawString(50, y, "Itinerary:")
    y -= 20
    for day, places in trip["itinerary"].items():
        c.drawString(50, y, f"{day}: {', '.join(places)}")
        y -= 20

    y -= 20
    c.drawString(50, y, "Budget:")
    y -= 20
    c.drawString(50, y, str(trip["budget"]))

    c.save()
    return file_path