
def generate_final_output(agent_result: dict, days: int):
    print(f"Generating final output with agent result for {days} days: {agent_result}")
    # This function would format the agent_result into a human-readable itinerary
    output_str = f"""**Your Personalized Travel Plan to {agent_result.get('destination', 'Unknown')}**\n\n"""
    output_str += f"Duration: {agent_result.get('days', 0)} days\n"
    output_str += f"Budget: ${agent_result.get('budget', 0)}\n\n"
    output_str += f"**Flights:** {agent_result.get('flight_details', dict()).get('message', 'N/A')}\n"
    output_str += f"**Hotels:** {agent_result.get('hotel_details', dict()).get('message', 'N/A')}\n"
    output_str += f"**Attractions:** {', '.join(agent_result.get('places_to_visit', []))}\n"
    output_str += f"**Weather:** {agent_result.get('weather_info', dict()).get('message', 'N/A')}\n"
    output_str += f"**Estimated Total Cost:** ${agent_result.get('total_estimated_cost', 'N/A')}\n\n"
    output_str += "*This is a placeholder output. Actual details would be generated by the agent's tools.*"
    return output_str

def print_expected_results(final_output: str):
    print("\n--- FINAL TRAVEL PLAN ---")
    print(final_output)
    print("-------------------------")
