# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cK3BtBs8aPIa58vyltguHCOXslXRaw3W
"""

from google.colab import drive
drive.mount('/content/drive')

import sys
sys.path.append("/content/drive/MyDrive/travel_agent")
import core
import agent

import core
import agent

app_path = "/content/drive/MyDrive/travel_agent/streamlit_app.py"

app_code = """
import streamlit as st
import sys
sys.path.append('/content/drive/MyDrive/travel_agent')

import core
import agent

st.set_page_config(page_title='Agentic AI Travel Planner')

st.title('🧭 Agentic AI Travel Planner')

source = st.text_input('Source city')
destination = st.text_input('Destination city')
days = st.number_input('Trip duration (days)', min_value=1, max_value=10, value=3)

preference = st.multiselect(
    'Choose your interests',
    ['Beaches','Temples','Shopping','Nature','Adventure']
)

if st.button('Generate Trip'):
    trip = core.plan_trip(source, destination, int(days))

    if 'error' in trip:
        st.error(trip['error'])
    else:
        st.success('Trip generated successfully')

        st.subheader('✈ Flight')
        st.write(trip['flight_selected'])

        st.subheader('🏨 Hotel')
        st.write(trip['hotel_selected'])

        st.subheader('🗺 Itinerary')
        st.write(trip['itinerary'])

        st.subheader('💰 Budget')
        st.write(trip['budget'])

        # Voice read budget
        if st.button('🔊 Read Budget'):
            core.speak_budget(trip)

        # Downloadable PDF
        if st.button('📥 Download PDF'):
            path = '/content/trip_plan.pdf'
            core.generate_pdf(trip, path)
            with open(path,'rb') as f:
                st.download_button('Download File', f, file_name='trip_plan.pdf')
"""

with open(app_path, "w") as f:
    f.write(app_code)

print("streamlit_app.py created successfully")

!streamlit run /content/drive/MyDrive/travel_agent/streamlit_app.py