# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cK3BtBs8aPIa58vyltguHCOXslXRaw3W
"""

from google.colab import drive
drive.mount('/content/drive')

app_path = "/content/drive/MyDrive/travel_agent/streamlit_app.py"

app_code = """
import streamlit as st
import agent
import core

st.set_page_config(page_title="Agentic AI Travel Planner")
st.title("🧭 Agentic AI Travel Planner")

source = st.text_input("Source city")
destination = st.text_input("Destination city")
days = st.number_input("Days",1,10,3)

preference = st.selectbox(
    "Preference",
    ["None","Beaches","Temples","Shopping","Nature","Adventure"]
)

if st.button("Plan trip"):
    response = agent.ask_agent(f"plan a {days} day trip from {source} to {destination}")
    st.write(response)

    trip = core.plan_trip(source, destination, days)

    st.success("Trip plan generated")

    st.subheader("Budget")
    st.write(trip["budget"])

    # 🔊 Voice read budget
    if st.button("Read Budget Aloud"):
        core.speak_budget(trip["budget"])
        st.info("Speaking...")

    # 📥 Export PDF
    if st.button("Download Trip Plan as PDF"):
        path = core.export_pdf(trip)
        with open(path, "rb") as f:
            st.download_button(
                label="Download PDF",
                data=f,
                file_name="trip_plan.pdf",
                mime="application/pdf"
            )"""


with open(app_path,"w") as f:
    f.write(app_code)

print("streamlit app saved")

!pip install pyngrok

from pyngrok import ngrok
# Replace 'YOUR_AUTHTOKEN' with your actual ngrok authtoken
ngrok.set_auth_token("35pir11lSH5XI1eaAdtDWDuoP9V_7SYe3ZAu9kz6VdA21VoA") # Uncomment this line and replace YOUR_AUTHTOKEN
public_url = ngrok.connect(8501)
print(public_url)

!streamlit run /content/drive/MyDrive/travel_agent/streamlit_app.py